services:
  # device_agent:
  #   image: spaneng/doover_device_agent:apps
  #   network_mode: host
  #   volumes:
  #     - ./dda_config.json:/var/lib/dds/agent/config.json

  # platform_iface:
  #   image: spaneng/doover_platform_iface:sim
  #   network_mode: host
  #   entrypoint: python3 -u platform_iface.py --type=sim

  power-management:
    build: ../
    restart: unless-stopped
    network_mode: host
    privileged: true  # Required for Bluetooth hardware access
    environment:
      - APP_KEY=solar_power_management-1
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
      # - CONFIG_FP=/app/simulators/app_config.json
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/dbus:/var/run/dbus
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
